# Site Settings
baseurl: ""
url: "https://suyeon-b.github.io"

# Blog Settings
theme_settings:
  title: Just do it!
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/img/me.jpg
    username: Suyeon Bak
    description: ì•ˆë…•í•˜ì„¸ìš”!:) <br>í•œê³„ê¹Œì§€ íŒŒê³ ë“¤ì–´ ì„±ì¥í•˜ëŠ” ë°•ìˆ˜ì—°ì…ë‹ˆë‹¤. ğŸ¦ˆ
    experience:
      - start: 2020-09
        end: 2021-08
        experience: í•œêµ­ì™¸êµ­ì–´ëŒ€í•™êµ ê¸€ë¡œë²Œìº í¼ìŠ¤ | í—ê°€ë¦¬ì–´ê³¼ í•™ë¶€ì¡°êµ
      - start: 2020-01
        end: 2020-07
        experience: ì‚¼ì„±ì „ì í—ê°€ë¦¬ ë²•ì¸ | ì¸ì‚¬ì´ë¬´íŒ€ ì¸í„´
      - start: 2017-02
        end: 2019-06
        experience: ì˜êµ­ EM í•™ì› | ì´ˆÂ·ì¤‘ë“±ë°˜ ìˆ˜í•™, ì˜ì–´ íšŒí™” ê°•ì‚¬
    education:
      - start: 2022-03
        end: 2022-08
        education: SW ì‚¬ê´€í•™êµ ì •ê¸€ | KAIST ë¹„í•™ìœ„ í”„ë¡œê·¸ë¨
      - start: 2017-02
        end: 2022-02
        education: í•œêµ­ì™¸êµ­ì–´ëŒ€í•™êµ ê¸€ë¡œë²Œ ìº í¼ìŠ¤ | í—ê°€ë¦¬ì–´ & ì»´í“¨í„°ê³µí•™
      - start: 2019-09
        end: 2019-12
        education: Balassi IntÃ©zet | Language & Culture Course

    # skills:
    #   - skill: HTML5 & CSS
    #     value: 85 # Percent value

  # Icons
  icons:
    email: "tndus4243@naver.com"
    linkedin: # Full URL
    github: suyeon-b
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube: /UCI8k3pjh5ZwySyf-mqoRZ9Q
    facebook:
    instagram: nosuyeonnolife/

  # Gitment comments
  gitment:
    username: Suyeon-B
    repo: Suyeon-B/comments
    client_id: 02caca6bbae1a7ad33a1
    client_secret: a2c9f08e73745f5c8f8208c9da78b6a7df8c6d26

# Google analytics
google_analytics: "G-66SKJ6STTN"

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
